### ISSUE TITLE
multiple message in two seconds - error

### ISSUE THREAD

**Issue by Ilovegym66** [phoeluga/ioBroker.synochat#6] opened 2022-04-30 15:26 UTC
Hi,
I have some scripts, there are reporting error messages, if there are more as one in a second, the Adapter reports this error and the message was NOT sendet:

`Unable to send message to Synology Chat REST API http://192.168.0.63:5000/webapi/entry.cgi!`

Can you add a cache with a queue for this, please ?

With my old script with http request this never happened, looks like some transfer delay things ..??

**Comment by phoeluga** [comment] 2022-05-15 09:29
The behavior is reproducible:

    2022-05-15 10:58:55.811 - debug: synochat.0 (202) State for object 'synochat.0.TestChannel.message' changed to value 'SynochatTest-01 - Iteration '1' 2022-05-15 10:58:55.763' with ack=false.
    2022-05-15 10:58:55.811 - debug: synochat.0 (202) Found channel for requested message to be sent to the Synology chat server with object id 'synochat.0.TestChannel.message'.
    2022-05-15 10:58:55.811 - debug: synochat.0 (202) Preparing REST API call for endpoint 'https://mychat.tld/webapi/entry.cgi'...
    2022-05-15 10:58:55.905 - debug: synochat.0 (202) State for object 'synochat.0.TestChannel.message' changed to value 'SynochatTest-01 - Iteration '2' 2022-05-15 10:58:55.863' with ack=false.
    2022-05-15 10:58:55.905 - debug: synochat.0 (202) Found channel for requested message to be sent to the Synology chat server with object id 'synochat.0.TestChannel.message'.
    2022-05-15 10:58:55.905 - debug: synochat.0 (202) Preparing REST API call for endpoint 'https://mychat.tld/webapi/entry.cgi'...
    2022-05-15 10:58:55.953 - debug: synochat.0 (202) https://mychat.tld/webapi/entry.cgi: 200 OK
    '{"success":true}'
    2022-05-15 10:58:55.953 - debug: synochat.0 (202) Successfully sent message to https://mychat.tld/webapi/entry.cgi.
    2022-05-15 10:58:55.955 - debug: synochat.0 (202) State for object 'synochat.0.TestChannel.message' changed to value 'SynochatTest-01 - Iteration '2' 2022-05-15 10:58:55.863' but ack flag is set. > Request will not be processed!
    2022-05-15 10:58:55.978 - debug: synochat.0 (202) https://mychat.tld/webapi/entry.cgi: 200 OK
    '{"error":{"code":411,"errors":"create post too fast"},"success":false}'
    2022-05-15 10:58:55.978 - error: synochat.0 (202) Unable to send message to Synology Chat REST API https://mychat.tld/webapi/entry.cgi!
    2022-05-15 10:58:55.978 - debug: synochat.0 (202) Message not successfully sent. > Lookup next channel for 'TestChannel' in the configured channels...
    2022-05-15 10:58:55.978 - debug: synochat.0 (202) Unable to find an incoming channel for the requested channel name 'TestChannel'! > Request will not be processed!

From the response returned by Synology Chat, it appears that the number of messages that can be sent in a given time interval is limited.

`2022-05-15 10:58:55.978 - debug: synochat.0 (202) https://mychat.tld/webapi/entry.cgi: 200 OK
'{"error":{"code":411,"errors":"create post too fast"},"success":false}'`

### Project Notes:

This behavior is caused by Synology Chat.
- The adapter works as expected
- A queuing of the messages before sending would be a possible solution.
- -> Checking the solution or possible implementations...

**Comment by phoeluga** [comment] 2022-05-15 09:35
@Ilovegym66 
Since this limitation is given by the Synology Chat, I would be interested to know the structure of the script you mentioned, as this one was able to send messages successfully in a short time (< 1 second).

Do your former scripts also use a queue to send the pending messages?

**Comment by Ilovegym66** [comment] 2022-05-15 13:37
Hi, 
it's a easy blockly what send the incoming text from a object to the syno with a http request. I have 3 of them for 3 different Topics ( Home, Security, Technical ). 
With the script I can send to all 3 in one time messages, with the adapter I got the errors. 
Here the script:
`var url, Nachricht;

// encode URL function
async function encodeURI2(url) {
    url = encodeURIComponent(url);
    return url;
}


on({id: "0_userdata.0.Servicemeldungen.Synochat"/*SynochatSweethome95*/, change: "ne"}, async function (obj) {
  var value = obj.state.val;
  var oldValue = obj.oldState.val;
  Nachricht = await encodeURI2((obj.state ? obj.state.val : ""));
  try {
    require("request")((['http://192.168.0.63:5000/webapi/entry.cgi?api=SYNO.Chat.External&method=incoming&version=2&token="tokendeleted"&payload={"text":"',Nachricht,'"}'].join(''))).on("error", function (e) {console.error(e);});
  } catch (e) { console.error(e); }
  setState("lgtv.1.states.popup"/*Show popup text on TV*/, (obj.state ? obj.state.val : ""));
  setState("lgtv.2.states.popup"/*Show popup text on TV*/, (obj.state ? obj.state.val : ""));
});`

The most actions are very fast messages coming is, if a door is unlocked and than opened and closed.
If I use the script, I got every message, If I use the adapter, some messages are lost..

**Comment by phoeluga** [comment] 2022-05-15 20:04
The described behavior will be addressed in the implementation in the upcoming version **`1.2.0`** -> #7.

The feature will cover:
- Delayed sending of messages has been added to work around the limitations of messages sent to the Synology Chat Server in a certain time interval.
- A message queue has been added to ensure that the order of messages to be sent is respected when the sending of messages is delayed.

Smoke tests are currently pending.
--> Release is planned for **CW 20**.

**Closed** 2022-05-17 13:30 UTC
Labels: enhancement, triaged, implemented
